### PR TITLE
Optimize Conway with a Summed Area Table

### PR DESCRIPTION
**Pull request by chrisib**
Simple performance optimization for Conway to use a Summed Area Table instead of iterating through the neighbourhoods of changed pixels. This should keep the framerate more stable.

Replaces https://github.com/Allen-Synthesis/EuroPi/pull/435, though the multi-threaded approach may be reintroduced later.

### CODE REVIEW

**Comment by chrisib** [comment]
Debugging a very strange problem that seems to occur after a few hours of continuous use:

```
45061: 'bool' object has no attribute 'field_sum'
Traceback (most recent call last):
  File "/lib/bootloader.py", line 186, in main
  File "/lib/contrib/conway.py", line 348, in main
  File "/lib/contrib/conway.py", line 271, in tick
  File "/lib/contrib/conway.py", line 219, in sum_cells
AttributeError: 'bool' object has no attribute 'field_sum'
```

The stack trace calls are
```
conway.py", line 348, in main: self.tick()
conway.py", line 271, in tick: num_neighbours = self.sum_cells(top, left, bottom, right)
conway.py", line 219, in sum_cells: a = self.field_sum[start_row - 1][start_col - 1]
```

It's consistently that line that breaks, but I haven't succeeded in any debugging inspections yet. Launching from the intepreter:
```python
>>> from contrib.conway import Conway
>>> c = Conway()
>>> c.main()
...
AttributeError: 'bool' object has no attribute 'field_sum'
```
re-running the offending function:
```python
>>> c.tick()
```
works _fine_. So it seems to be some sort of runtime memory issue? Maybe there's a pointer that's going squirrely? _Something_ is going wrong, but I haven't figured out exactly _what_ or _why_ yet.

**Comment by chrisib** [comment]
Was using uPython 1.24.1, so let's see if it goes away after upgrading to 1.25.0...
